FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG SERVICE_PROJECT
WORKDIR /src
COPY . .
RUN dotnet restore "${SERVICE_PROJECT}"
RUN dotnet publish "${SERVICE_PROJECT}" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
ARG SERVICE_DLL
ARG SERVICE_PROJECT
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENV APP_DLL=${SERVICE_DLL}
EXPOSE 8080
ENTRYPOINT dotnet $APP_DLL
