namespace EMS.Domain.Entities;

/// <summary>
/// Abstract base entity class that all domain entities inherit from
/// Provides common properties for auditing, soft delete, and identity
/// 
/// Key Features:
/// - Primary Key (Id)
/// - Audit Timestamps (CreatedAt, UpdatedAt)
/// - Soft Delete (IsDeleted, DeletedAt)
/// - Version tracking for optimistic concurrency
/// 
/// Usage:
/// public class Student : BaseEntity { }
/// public class Course : BaseEntity { }
/// </summary>
public abstract class BaseEntity
{
    /// <summary>
    /// Primary identifier for the entity
    /// Auto-generated by database (IDENTITY)
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Timestamp when record was created (UTC)
    /// Set automatically by database or application
    /// Never changes after creation
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Timestamp when record was last modified
    /// Updated every time record is modified
    /// Null if never modified since creation
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Soft delete flag
    /// Instead of deleting records, we mark them as deleted
    /// 
    /// Why soft delete?
    /// - Preserve data integrity (foreign key references)
    /// - Maintain audit trail
    /// - Can restore deleted records if needed
    /// - Comply with data retention policies
    /// 
    /// Queries should always filter: WHERE IsDeleted = false
    /// </summary>
    public bool IsDeleted { get; set; } = false;

    /// <summary>
    /// Timestamp when record was deleted (soft delete)
    /// Null if not deleted
    /// Used for audit trail and recovery
    /// </summary>
    public DateTime? DeletedAt { get; set; }

    /// <summary>
    /// Row version for optimistic concurrency control
    /// Updated by database on every change
    /// Prevents lost updates when multiple users edit simultaneously
    /// 
    /// Example Scenario:
    /// 1. User A reads Grade (RowVersion = 1)
    /// 2. User B reads Grade (RowVersion = 1)
    /// 3. User B updates Grade ? RowVersion becomes 2
    /// 4. User A tries to update ? Fails because RowVersion is 2 (conflict detected)
    /// </summary>
    public byte[]? RowVersion { get; set; }

    /// <summary>
    /// Soft deletes the entity by setting IsDeleted = true
    /// Used instead of permanent deletion
    /// </summary>
    public void SoftDelete()
    {
        IsDeleted = true;
        DeletedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Restores a soft-deleted entity
    /// </summary>
    public void Restore()
    {
        IsDeleted = false;
        DeletedAt = null;
    }

    /// <summary>
    /// Marks when the entity was last updated
    /// Called before saving changes
    /// </summary>
    public void UpdateTimestamp()
    {
        UpdatedAt = DateTime.UtcNow;
    }
}
